### ISSUE TITLE
[Composite.Media.YouTubeChannel] The function preview showing a black box for the player in the editor

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-Packages#3]
**Repro**:

1. Insert the functions on a page
2. View the function preview in the editor.
3. Compare to what you see in the page preview or on the published page.
 
**Expected**: It shows something similar to the real view in a page
**Actual**: It shows a black box for the player

**Comment by mawtex** [comment]
The issue here is that the tool generating screenshots (PhantomJS - a headless browser based on WebKit) does not ship with flash. A fix here is that the package examine RenderingReason http://docs.composite.net/Functions/Composite-C1-API/Rendering-Reason and emit another result.

This result could be a thumbnail based on http://img.youtube.com/vi/FhdTTLUVEcI/0.jpg - stretched to fit. Bonus points for an overlay that mimic the YouTube play button

**Comment by InnaBoitsun** [comment]
@mawtex there is another issue - https://github.com/Orckestra/C1-CMS/issues/24
that FunctionPreview also doesn't show images form external URLs

**Comment by wwwysocki** [comment]
Verified v. 2.0.9
